Mark message-ix 1.0.0 as broken
conda-forge/admin-requests pull request #385
Opened 2022-01-31 08:59 UTC by LauWien

Conda doesn't install the latest message-ix package on windows-latest by default (current version 3.4.0), but rather installs message-ix version 1.0.0, please see [here](https://github.com/iiasa/message_ix/runs/5001443802?check_suite_focus=true) and the corresponding workflow step [here](https://github.com/iiasa/message_ix/blob/main/.github/workflows/conda.yaml#L71). Relevant PR https://github.com/iiasa/message_ix/pull/541.

Ping @conda-forge/message-ix 

Checklist:

* [x] Make sure your package is in the right spot (`broken/*` for adding the
  `broken` label, `not_broken/*` for removing the `broken` label, or `token_reset/*`
  for token resets)
* [x] Added a description of the problem with the package in the PR description.
* [x] Added links to any relevant issues/PRs in the PR description.
* [x] Pinged the team for the package for their input.

2022-01-31 09:38 UTC, jaimergp commented
I don't think `message-ix` is broken at all. It's more like the solver is only able to accommodate that version in your environment, possibly because you are starting with the [full Anaconda distribution ](https://github.com/iiasa/message_ix/runs/5001443802?check_suite_focus=true#step:3:12)and then installing things on top (coming from conda-forge, so the solver is already struggling). I would recommend using something like `conda-incubator/setup-miniconda` (or change your action to use Miniconda instead of Anaconda) and then add only the things you need.

2022-01-31 09:51 UTC, khaeru commented
> I would recommend using something like `conda-incubator/setup-miniconda` (or change your action to use Miniconda instead of Anaconda) and then add only the things you need.

If you look at the other jobs in the same workflow, you'll see the problem also occurs with Miniconda, e.g. [here](https://github.com/iiasa/message_ix/runs/5001443931?check_suite_focus=true).

2022-01-31 09:56 UTC, jaimergp commented
Oh, my bad. I'd say we can't still just mark it as broken because some people might rely on it, so maybe we need to investigate what's missing in the metadata and issue a repodata patch. Thoughts @conda-forge/core?

2022-01-31 10:29 UTC, jaimergp commented
> conda config --prepend channels conda-forge adds the arch-specific channel above the noarch channel

This is not entirely accurate. A channel consists of subdirectories, usually a platform specific one _and_ the noarch one. Adding conda-forge with prepend implies you are adding conda-forge/linux-64 (on Linux, that is) and conda-forge/noarch, but these are not affected by channel priority. This is handled by the solver internally. Whether noarch is preferred to arch for a specific package (or viceversa) depends on several factors, but the gist is that you are not changing that by adding conda-forge first. 

Like I said, _ideally_ we would fix the metadata that leads to 1.0.0 being preferred (there must be an incompatible spec added that makes the solver go back all the way to version 1, which is usually difficult because larger versions are strongly preferred). _But_ if you are confident `message-ix 1` won't be missed too much, I am +1 here. We can always revert if it goes wrong.

2022-01-31 11:08 UTC, khaeru commented
> A channel consists of subdirectories, usually a platform specific one _and_ the noarch one. Adding conda-forge with prepend implies you are adding conda-forge/linux-64 (on Linux, that is) and conda-forge/noarch, but these are not affected by channel priority. This is handled by the solver internally.

Okay, that's very good to know—thanks for the explanation. This was not clear to us from reading the documentation, e.g. the above-linked page on “Managing channels” uses phrasing that suggests every entry in the “channel list” is a distinct “channel” rather than a “subdirectory within an (equivalent) channel”.

> the metadata that leads to 1.0.0 being preferred (there must be an incompatible spec added that makes the solver go back all the way to version 1…

I don't know anything about the metadata (format, how it affects the solver's behaviour, etc.)—if there is a HOWTO or docs that you can link us to, then @LauWien could try to investigate/diagnose. Otherwise we'd appreciate approval of the PR 🙏🏾

2022-01-31 13:29 UTC, beckermr commented
Yeah this is a solver issue, not a broken package. We should not merge this yet until we know why the solver is preferring the older one.

2022-01-31 14:02 UTC, khaeru commented
> We should not merge this yet until we know why the solver is preferring the older one.

As I asked in the last comment: is there any guide to how to go about answering that "why" question? Without one, @LauWien/I would not know where to start, and can only wait for someone else to investigate.

2022-01-31 14:15 UTC, beckermr commented
Sure! So the first step is to make the simplest environment you can that shows the issue. It should be a clean env that is brand new. After that, remove other packages in the env one by one. If removing one causes the issue to go away, then I'd check the dependencies of that one vs the problematic package to figure out why they conflict.  

To find deps you can download and unpack various packages by hand from anaconda.org or go look at the repo data.json. The repodata.json is the authoritative source of info but harder to get. 

I'm on my phone, but I can post the url to the json file in a bit.

2022-02-01 12:40 UTC, jaimergp commented
I'll give it a shot.

With conda, you can simulate the installation on Windows like this:

```
$ CONDA_SUBDIR=win-64 conda create --quiet --name testenv --dry-run -c defaults "message-ix" JPype1=1.2.1 pytest asyncssh sphinx
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/jrodriguez/.local/anaconda/envs/testenv

  added / updated specs:
    - asyncssh
    - jpype1=1.2.1
    - message-ix
    - pytest
    - sphinx


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    alabaster-0.7.12           |     pyhd3eb1b0_0          16 KB  defaults
    argon2-cffi-20.1.0         |   py38h2bbff1b_1          49 KB  defaults
    async_generator-1.10       |     pyhd3eb1b0_0          23 KB  defaults
    asyncssh-2.9.0             |     pyhd8ed1ab_0         223 KB  conda-forge
    atomicwrites-1.4.0         |             py_0          11 KB  defaults
    attrs-21.4.0               |     pyhd3eb1b0_0          51 KB  defaults
    babel-2.9.1                |     pyhd3eb1b0_0         5.5 MB  defaults
    backcall-0.2.0             |     pyhd3eb1b0_0          13 KB  defaults
    blas-1.0                   |              mkl           6 KB  defaults
    bleach-4.1.0               |     pyhd3eb1b0_0         123 KB  defaults
    bottleneck-1.3.2           |   py38h2a96729_1         106 KB  defaults
    brotli-1.0.9               |       ha925a31_2         332 KB  defaults
    brotlipy-0.7.0             |py38h2bbff1b_1003         412 KB  defaults
    ca-certificates-2021.10.26 |       haa95532_4         116 KB  defaults
    certifi-2021.10.8          |   py38haa95532_2         152 KB  defaults
    cffi-1.15.0                |   py38h2bbff1b_1         223 KB  defaults
    charset-normalizer-2.0.4   |     pyhd3eb1b0_0          35 KB  defaults
    colorama-0.4.4             |     pyhd3eb1b0_0          21 KB  defaults
    cryptography-36.0.0        |   py38h21b164f_0         1.0 MB  defaults
    cycler-0.11.0              |     pyhd3eb1b0_0          12 KB  defaults
    cython-0.29.25             |   py38h604cdb4_0         1.8 MB  defaults
    debugpy-1.5.1              |   py38hd77b12b_0         2.6 MB  defaults
    decorator-5.1.1            |     pyhd3eb1b0_0          12 KB  defaults
    defusedxml-0.7.1           |     pyhd3eb1b0_0          23 KB  defaults
    docutils-0.17.1            |   py38haa95532_1         696 KB  defaults
    entrypoints-0.3            |           py38_0          11 KB  defaults
    fonttools-4.25.0           |     pyhd3eb1b0_0         632 KB  defaults
    freetype-2.10.4            |       hd328e21_0         466 KB  defaults
    icu-58.2                   |       ha925a31_3         9.4 MB  defaults
    idna-3.3                   |     pyhd3eb1b0_0          49 KB  defaults
    imagesize-1.3.0            |     pyhd3eb1b0_0           9 KB  defaults
    importlib-metadata-4.8.2   |   py38haa95532_0          40 KB  defaults
    importlib_metadata-4.8.2   |       hd3eb1b0_0          12 KB  defaults
    iniconfig-1.1.1            |     pyhd3eb1b0_0           8 KB  defaults
    intel-openmp-2021.4.0      |    haa95532_3556         2.2 MB  defaults
    ipykernel-6.4.1            |   py38haa95532_1         192 KB  defaults
    ipython-7.29.0             |   py38hd4e2768_0        1017 KB  defaults
    ipython_genutils-0.2.0     |     pyhd3eb1b0_1          27 KB  defaults
    ipywidgets-7.6.5           |     pyhd3eb1b0_1         105 KB  defaults
    ixmp-0.1.2                 |                0         6.9 MB  conda-forge
    jedi-0.18.0                |   py38haa95532_1         910 KB  defaults
    jinja2-3.0.2               |     pyhd3eb1b0_0         110 KB  defaults
    jpeg-9d                    |       h2bbff1b_0         283 KB  defaults
    jpype1-1.2.1               |   py38h59b6b97_0         340 KB  defaults
    jsonschema-3.2.0           |     pyhd3eb1b0_2          47 KB  defaults
    jupyter-1.0.0              |           py38_7           8 KB  defaults
    jupyter_client-7.1.2       |     pyhd3eb1b0_0          93 KB  defaults
    jupyter_console-6.4.0      |     pyhd3eb1b0_0          23 KB  defaults
    jupyter_core-4.9.1         |   py38haa95532_0          91 KB  defaults
    jupyterlab_pygments-0.1.2  |             py_0           8 KB  defaults
    jupyterlab_widgets-1.0.0   |     pyhd3eb1b0_1         109 KB  defaults
    kiwisolver-1.3.1           |   py38hd77b12b_0          52 KB  defaults
    krb5-1.19.2                |       h5b6d351_0         697 KB  defaults
    libpng-1.6.37              |       h2a8f88b_0         333 KB  defaults
    libtiff-4.2.0              |       hd0e1b90_0         786 KB  defaults
    libwebp-1.2.0              |       h2bbff1b_0         643 KB  defaults
    lz4-c-1.9.3                |       h2bbff1b_1         132 KB  defaults
    m2w64-gcc-libgfortran-5.3.0|                6         342 KB  conda-forge
    m2w64-gcc-libs-5.3.0       |                7         520 KB  conda-forge
    m2w64-gcc-libs-core-5.3.0  |                7         214 KB  conda-forge
    m2w64-gmp-6.1.0            |                2         726 KB  conda-forge
    m2w64-libwinpthread-git-5.0.0.4634.697f757|                2          31 KB  conda-forge
    markupsafe-2.0.1           |   py38h2bbff1b_0          24 KB  defaults
    matplotlib-3.5.0           |   py38haa95532_0          28 KB  defaults
    matplotlib-base-3.5.0      |   py38h6214cd6_0         5.6 MB  defaults
    matplotlib-inline-0.1.2    |     pyhd3eb1b0_2          12 KB  defaults
    message-ix-1.0.0           |                3          82 KB  conda-forge
    mistune-0.8.4              |py38he774522_1000          55 KB  defaults
    mkl-2021.4.0               |     haa95532_640       114.9 MB  defaults
    mkl-service-2.4.0          |   py38h2bbff1b_0          51 KB  defaults
    mkl_fft-1.3.1              |   py38h277e83a_0         139 KB  defaults
    mkl_random-1.2.2           |   py38hf11a4ad_0         225 KB  defaults
    more-itertools-8.12.0      |     pyhd3eb1b0_0          49 KB  defaults
    msys2-conda-epoch-20160418 |                1           3 KB  conda-forge
    munkres-1.1.4              |             py_0          13 KB  defaults
    nbclient-0.5.3             |     pyhd3eb1b0_0          62 KB  defaults
    nbconvert-6.1.0            |   py38haa95532_0         500 KB  defaults
    nbformat-5.1.3             |     pyhd3eb1b0_0          44 KB  defaults
    nest-asyncio-1.5.1         |     pyhd3eb1b0_0          10 KB  defaults
    notebook-6.4.6             |   py38haa95532_0         4.5 MB  defaults
    numexpr-2.8.1              |   py38hb80d3ca_0         118 KB  defaults
    numpy-1.21.2               |   py38hfca59bb_0          24 KB  defaults
    numpy-base-1.21.2          |   py38h0829f74_0         4.4 MB  defaults
    olefile-0.46               |     pyhd3eb1b0_0          34 KB  defaults
    openjdk-11.0.13            |       h2bbff1b_0       301.3 MB  defaults
    openssl-1.1.1m             |       h2bbff1b_0         4.8 MB  defaults
    packaging-21.3             |     pyhd3eb1b0_0          36 KB  defaults
    pandas-1.3.5               |   py38h6214cd6_0         8.6 MB  defaults
    pandocfilters-1.5.0        |     pyhd3eb1b0_0          11 KB  defaults
    parso-0.8.3                |     pyhd3eb1b0_0          70 KB  defaults
    pickleshare-0.7.5          |  pyhd3eb1b0_1003          13 KB  defaults
    pillow-8.4.0               |   py38hd45dc43_0         911 KB  defaults
    pluggy-0.13.1              |   py38haa95532_0          34 KB  defaults
    prometheus_client-0.12.0   |     pyhd3eb1b0_0          47 KB  defaults
    prompt-toolkit-3.0.20      |     pyhd3eb1b0_0         259 KB  defaults
    prompt_toolkit-3.0.20      |       hd3eb1b0_0          12 KB  defaults
    py-1.10.0                  |     pyhd3eb1b0_0          76 KB  defaults
    py [...]

2022-02-01 12:44 UTC, beckermr commented
Nice! Are you all using strict channel priority? We try our best but cannot formally support defaults before conda-forge due to various reasons.

2022-02-01 12:48 UTC, jaimergp commented
For completeness:

```
$ conda info

     active environment : base
    active env location : $HOME/.local/anaconda
            shell level : 1
       user config file : $HOME/.condarc
 populated config files : $HOME/.local/anaconda/.condarc
                          $HOME/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.9.4.final.0
       virtual packages : __osx=11.2.3=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : $HOME/.local/anaconda  (writable)
      conda av data dir : $HOME/.local/anaconda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/label/rust_dev/osx-arm64
                          https://conda.anaconda.org/conda-forge/label/rust_dev/noarch
                          https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : $HOME/.local/anaconda/pkgs
                          $HOME/.conda/pkgs
       envs directories : $HOME/.local/anaconda/envs
                          $HOME/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.1 requests/2.26.0 CPython/3.9.4 Darwin/20.3.0 OSX/11.2.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False


$ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: False
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_conda_downgrades: False
allow_cycles: True
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_activate_base: True
auto_stack: 0
auto_update_conda: False
bld_path: 
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: strict
channels:
  - conda-forge/label/rust_dev
  - conda-forge
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
conda_build: {}
create_default_packages: []
croot: $HOME/.local/anaconda/conda-bld
custom_channels:
  pkgs/main: https://repo.anaconda.com
  pkgs/r: https://repo.anaconda.com
  $HOME/.local/anaconda/conda-bld: file://
  pkgs/pro: https://repo.anaconda.com
custom_multichannels:
  defaults: 
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
  local: 
    - file://$HOME/.local/anaconda/conda-bld
debug: False
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
default_python: 3.9
default_threads: None
deps_modifier: not_set
dev: False
disallowed_packages: []
download_only: False
dry_run: False
enable_private_envs: False
env_prompt: ({default_env}) 
envs_dirs:
  - $HOME/.local/anaconda/envs
  - $HOME/.conda/envs
error_upload_url: https://conda.io/conda-post/unexpected-error
execute_threads: 1
extra_safety_checks: False
force: False
force_32bit: False
force_reinstall: False
force_remove: False
ignore_pinned: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
migrated_custom_channels: {}
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pip_interop_enabled: False
pkgs_dirs:
  - $HOME/.local/anaconda/pkgs
  - $HOME/.conda/pkgs
proxy_servers: {}
quiet: False
remote_backoff_factor: 1
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
repodata_fns:
  - current_repodata.json
  - repodata.json
repodata_threads: None
report_errors: None
restore_free_channel: False
rollback_enabled: True
root_prefix: $HOME/.local/anaconda
safety_checks: warn
sat_solver: pycosat
separate_format_cache: False
shortcuts: True
show_channel_urls: True
signing_metadata_url_base: https://repo.anaconda.com/pkgs/main
solver_ignore_timestamps: False
ssl_verify: True
subdir: osx-arm64
subdirs:
  - osx-arm64
  - noarch
target_prefix_override: 
track_features: []
unsatisfiable_hints: True
unsatisfiable_hints_check_depth: 2
update_modifier: update_specs
use_index_cache: False
use_local: False
use_only_tar_bz2: False
verbosity: 0
verify_threads: 1
whitelist_channels: []
```

2022-02-01 14:50 UTC, LauWien commented
Many thanks both of you for investigating further!

Yesterday I tried out as suggested.

```
(base) PS C:\Users\laura> conda create --name message_env_2
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\laura\anaconda3\envs\message_env_2



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate message_env_2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS C:\Users\laura> conda activate message_env_2
(message_env_2) PS C:\Users\laura> conda install message-ix
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\laura\anaconda3\envs\message_env_2

  added / updated specs:
    - message-ix


The following NEW packages will be INSTALLED:

  argon2-cffi        conda-forge/noarch::argon2-cffi-21.3.0-pyhd8ed1ab_0
  argon2-cffi-bindi~ conda-forge/win-64::argon2-cffi-bindings-21.2.0-py310he2412df_1
  asttokens          conda-forge/noarch::asttokens-2.0.5-pyhd8ed1ab_0
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  backcall           conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0
  backports          conda-forge/noarch::backports-1.0-py_2
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.4-pyhd8ed1ab_0
  black              conda-forge/noarch::black-22.1.0-pyhd8ed1ab_0
  bleach             conda-forge/noarch::bleach-4.1.0-pyhd8ed1ab_0
  brotli             conda-forge/win-64::brotli-1.0.9-h8ffe710_6
  brotli-bin         conda-forge/win-64::brotli-bin-1.0.9-h8ffe710_6
  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2021.10.8-h5b45459_0
  certifi            conda-forge/win-64::certifi-2021.10.8-py310h5588dad_1
  cffi               conda-forge/win-64::cffi-1.15.0-py310hcbf9ad4_0
  click              conda-forge/win-64::click-8.0.3-py310h5588dad_1
  colorama           conda-forge/noarch::colorama-0.4.4-pyh9f0ad1d_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  cython             conda-forge/win-64::cython-0.29.27-py310h8a704f9_0
  dataclasses        conda-forge/noarch::dataclasses-0.8-pyhc8e2a94_3
  debugpy            conda-forge/win-64::debugpy-1.5.1-py310h8a704f9_0
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
  defusedxml         conda-forge/noarch::defusedxml-0.7.1-pyhd8ed1ab_0
  entrypoints        conda-forge/noarch::entrypoints-0.3-pyhd8ed1ab_1003
  executing          conda-forge/noarch::executing-0.8.2-pyhd8ed1ab_0
  flit-core          conda-forge/noarch::flit-core-3.6.0-pyhd8ed1ab_0
  fonttools          conda-forge/win-64::fonttools-4.29.0-py310he2412df_0
  freetype           conda-forge/win-64::freetype-2.10.4-h546665d_1
  icu                conda-forge/win-64::icu-68.2-h0e60522_0
  importlib-metadata conda-forge/win-64::importlib-metadata-4.10.1-py310h5588dad_0
  importlib_resourc~ conda-forge/noarch::importlib_resources-5.4.0-pyhd8ed1ab_0
  intel-openmp       conda-forge/win-64::intel-openmp-2022.0.0-h57928b3_3663
  ipykernel          conda-forge/win-64::ipykernel-6.7.0-py310hbbfc1a7_0
  ipython            conda-forge/win-64::ipython-8.0.1-py310h5588dad_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.6.5-pyhd8ed1ab_0
  ixmp               conda-forge/win-64::ixmp-0.1.2-0
  jbig               conda-forge/win-64::jbig-2.1-h8d14728_2003
  jedi               conda-forge/win-64::jedi-0.18.1-py310h5588dad_0
  jinja2             conda-forge/noarch::jinja2-3.0.3-pyhd8ed1ab_0
  jpeg               conda-forge/win-64::jpeg-9e-h8ffe710_0
  jpype1             conda-forge/win-64::jpype1-1.3.0-py310h476a331_2
  jsonschema         conda-forge/noarch::jsonschema-4.4.0-pyhd8ed1ab_0
  jupyter            conda-forge/win-64::jupyter-1.0.0-py310h5588dad_7
  jupyter_client     conda-forge/noarch::jupyter_client-7.1.2-pyhd8ed1ab_0
  jupyter_console    conda-forge/noarch::jupyter_console-6.4.0-pyhd8ed1ab_0
  jupyter_core       conda-forge/win-64::jupyter_core-4.9.1-py310h5588dad_1
  jupyterlab_pygmen~ conda-forge/noarch::jupyterlab_pygments-0.1.2-pyh9f0ad1d_0
  jupyterlab_widgets conda-forge/noarch::jupyterlab_widgets-1.0.2-pyhd8ed1ab_0
  kiwisolver         conda-forge/win-64::kiwisolver-1.3.2-py310h476a331_1
  lcms2              conda-forge/win-64::lcms2-2.12-h2a16943_0
  lerc               conda-forge/win-64::lerc-3.0-h0e60522_0
  libblas            conda-forge/win-64::libblas-3.9.0-13_win64_mkl
  libbrotlicommon    conda-forge/win-64::libbrotlicommon-1.0.9-h8ffe710_6
  libbrotlidec       conda-forge/win-64::libbrotlidec-1.0.9-h8ffe710_6
  libbrotlienc       conda-forge/win-64::libbrotlienc-1.0.9-h8ffe710_6
  libcblas           conda-forge/win-64::libcblas-3.9.0-13_win64_mkl
  libclang           conda-forge/win-64::libclang-11.1.0-default_h5c34c98_1
  libdeflate         conda-forge/win-64::libdeflate-1.8-h8ffe710_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  liblapack          conda-forge/win-64::liblapack-3.9.0-13_win64_mkl
  libpng             conda-forge/win-64::libpng-1.6.37-h1d00b33_2
  libsodium          conda-forge/win-64::libsodium-1.0.18-h8d14728_1
  libtiff            conda-forge/win-64::libtiff-4.3.0-hd413186_2
  libzlib            conda-forge/win-64::libzlib-1.2.11-h8ffe710_1013
  lz4-c              conda-forge/win-64::lz4-c-1.9.3-h8ffe710_1
  markupsafe         conda-forge/win-64::markupsafe-2.0.1-py310he2412df_1
  matplotlib         conda-forge/win-64::matplotlib-3.5.1-py310h5588dad_0
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.5.1-py310h79a7439_0
  matplotlib-inline  conda-forge/noarch::matplotlib-inline-0.1.3-pyhd8ed1ab_0
  message-ix         conda-forge/win-64::message-ix-1.0.0-3
  mistune            conda-forge/win-64::mistune-0.8.4-py310he2412df_1005
  mkl                conda-forge/win-64::mkl-2022.0.0-h0e2418a_796
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0
  mypy_extensions    conda-forge/win-64::mypy_extensions-0.4.3-py310h5588dad_4
  nbclient           conda-forge/noarch::nbclient-0.5.10-pyhd8ed1ab_1
  nbconvert          conda-forge/win-64::nbconvert-6.4.1-py310h5588dad_0
  nbformat           conda-forge/noarch::nbformat-5.1.3-pyhd8ed1ab_0
  nest-asyncio       conda-forge/noarch::nest-asyncio-1.5.4-pyhd8ed1ab_0
  notebook           conda-forge/noarch::notebook-6.4.8-pyha770c72_0
  numpy              conda-forge/win-64::numpy-1.22.1-py310hcae7c84_0
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openjdk            conda-forge/win-64::openjdk-11.0.9.1-h57928b3_1
  openjpeg           conda-forge/win-64::openjpeg-2.4.0-hb211442_1
  openssl            conda-forge/win-64::openssl-1.1.1l-h8ffe710_0
  packaging          conda-forge/noarch::packaging-21.3-pyhd8ed1ab_0
  pandas             conda-forge/win-64::pandas-1.4.0-py310hf5e1058_0
  pandoc             conda-forge/win-64::pandoc-2.17.1.1-h57928b3_0
  pandocfilters      conda-forge/noarch::pandocfilters-1.5.0-pyhd8ed1ab_0
  parso              conda-forge/noarch::parso-0.8.3-pyhd8ed1ab_0
  pathspec           conda-forge/noarch::pathspec-0.9.0-pyhd8ed1ab_0
  pickleshare        conda-forge/noarch::pickleshare-0.7.5-py_1003
  pillow             conda-forge/win-64::pillow-8.4.0-py310h22f3323_0
  pip                conda-forge/noarch::pip-22.0.2-pyhd8ed1ab_0
  platformdirs       conda-forge/noarch::platformdirs-2.3.0-py [...]

2022-02-01 15:50 UTC, jaimergp commented
I am not surprised `setuptools` is causing the issue here. The `<60` restraint some projects have might be straining the solver a bit too much, and if we add defaults+conda-forge with flexible priority... recipe for complications like this 😬

2022-02-01 16:23 UTC, LauWien commented
My apologies!
```

(message_env_2) PS C:\Users\laura> conda info

     active environment : message_env_2
    active env location : C:\Users\laura\anaconda3\envs\message_env_2
            shell level : 2
       user config file : C:\Users\laura\.condarc
 populated config files : C:\Users\laura\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\laura\anaconda3  (writable)
      conda av data dir : C:\Users\laura\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
          package cache : C:\Users\laura\anaconda3\pkgs
                          C:\Users\laura\.conda\pkgs
                          C:\Users\laura\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\laura\anaconda3\envs
                          C:\Users\laura\.conda\envs
                          C:\Users\laura\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.19042
          administrator : False
             netrc file : None
           offline mode : False
```

2022-02-01 16:40 UTC, LauWien commented
> you got it to solve and so I suspect there is simply a difference in the config locally.

The issue is unfortunately not only locally, but also, as mentioned, in the test suit [here](https://github.com/iiasa/message_ix/runs/5022006886?check_suite_focus=true).

I'm currently testing if 
```
conda create --quiet --name testenv --dry-run -c conda-forge -c defaults message-ix JPype1=1.2.1 pytest asyncssh sphinx
``` 
also works for me locally as only with this it worked for @jaimergp with conda.

2022-02-01 16:42 UTC, beckermr commented
kk. BTW, the python 3.1 error is a bug due to python 3.10 have three characters. You'll want to update conda locally I think?

2022-02-01 16:51 UTC, LauWien commented
> python 3.1 error is a bug due to python 3.10 have three characters

Ah I see, that makes sense, thank you!

I guess what I would like to have is, the latest package installed if I use the following command. 
```
conda install message-ix
```
This would be great so our tests on GHA pass and users install directly the latest version of `message-ix`.

2022-02-01 17:34 UTC, jaimergp commented
@LauWien Can you add the `conda config --show` line to your CI? It _should_ work with strict priority. Let's see if that's the case.

2022-02-02 09:09 UTC, LauWien commented
As suggested I implemented `conda config --show` in https://github.com/iiasa/message_ix/pull/554 and the priority was set to flexible, please see [here ](https://github.com/iiasa/message_ix/runs/5033949838?check_suite_focus=true). With setting now the channel priority to strict in https://github.com/iiasa/message_ix/pull/554/commits/b48243451b8d2d2e0f14c1d669ddedd69a7a43f9, conda is unfortunately still installing `messag-ix=1.0.0`, please see [here](https://github.com/iiasa/message_ix/runs/5034018916?check_suite_focus=true) ;/

2022-02-02 10:10 UTC, beckermr commented
@conda-forge/core can you help us with this weird solver issue? We seem to be stuck.

2022-02-04 06:54 UTC, LauWien commented
Any news here? Many thanks in advance!

2022-02-04 12:07 UTC, beckermr commented
No sorry. I very little time to debug issues like this so I'm afraid I won't be of much more help here.

2022-02-04 14:12 UTC, LauWien commented
> No sorry. I very little time to debug issues like this so I'm afraid I won't be of much more help here.

Many thanks for letting us know! Do you think @conda-forge/core would have more time to support here? Otherwise we'd appreciate the approval of this PR.

2022-02-04 14:49 UTC, beckermr commented
Again this is a solver issue and we cannot approve this pr. 

Please continue to debug as we have outlined above.

2022-02-04 14:49 UTC, beckermr requested changes
This is a solver issue not a broken package.

2022-02-06 11:09 UTC, khaeru commented
> This is a solver issue not a broken package.

On which repository should we re-file the issue to bring it to the attention of the appropriate persons?

2022-02-06 15:56 UTC, beckermr commented
This is the right spot for the issue. What needs to be done is for someone to sit down and figure out what is conflicting in the repo data to make this happen. Sorry I can't be of more help right now.

2022-02-06 16:57 UTC, isuruf commented
Probably https://github.com/conda/conda-build/issues/4104.

https://github.com/conda/infra/discussions/514 will workaround this.

2022-02-07 06:56 UTC, LauWien commented
> Probably [conda/conda-build#4104](https://github.com/conda/conda-build/issues/4104).
> 
> [conda/infra#514](https://github.com/conda/infra/discussions/514) will workaround this.

Many thanks @isuruf!

2022-03-23 16:56 UTC, isuruf commented
Should be fixed now

2022-03-24 11:14 UTC, LauWien commented
Hi there, thank you for following up on this. 
Unfortunately it is still not working as expected. The default on installing `conda install message-ix` is still version 1.0.0 `message-ix         conda-forge/win-64::message-ix-1.0.0-3`

Please see the following
```

(base) PS C:\Users\laura>
(base) PS C:\Users\laura>
(base) PS C:\Users\laura> conda config --prepend channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(base) PS C:\Users\laura> conda config --set channel_priority strict
(base) PS C:\Users\laura> conda create --name message_env_2022
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.12.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\laura\anaconda3\envs\message_env_2022



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate message_env_2022
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS C:\Users\laura> conda activate message_env_2022
(message_env_2022) PS C:\Users\laura> conda install message-ix
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.12.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\laura\anaconda3\envs\message_env_2022

  added / updated specs:
    - message-ix


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    beautifulsoup4-4.10.0      |     pyha770c72_0          77 KB  conda-forge
    cython-0.29.28             |  py310h8a704f9_0         1.9 MB  conda-forge
    entrypoints-0.4            |     pyhd8ed1ab_0           9 KB  conda-forge
    executing-0.8.3            |     pyhd8ed1ab_0          18 KB  conda-forge
    flit-core-3.7.1            |     pyhd8ed1ab_0          44 KB  conda-forge
    fonttools-4.31.2           |  py310he2412df_0         1.5 MB  conda-forge
    icu-69.1                   |       h0e60522_0        16.4 MB  conda-forge
    importlib-metadata-4.11.3  |  py310h5588dad_0          34 KB  conda-forge
    ipykernel-6.9.2            |  py310hbbfc1a7_0         186 KB  conda-forge
    ipython-8.1.1              |  py310h5588dad_0         1.1 MB  conda-forge
    ipywidgets-7.7.0           |     pyhd8ed1ab_0         103 KB  conda-forge
    jupyter_console-6.4.3      |     pyhd8ed1ab_0          23 KB  conda-forge
    jupyter_core-4.9.2         |  py310h5588dad_0         106 KB  conda-forge
    jupyterlab_widgets-1.1.0   |     pyhd8ed1ab_0         133 KB  conda-forge
    kiwisolver-1.4.0           |  py310h476a331_0          58 KB  conda-forge
    libclang-13.0.1            |default_h81446c8_0        23.7 MB  conda-forge
    libdeflate-1.10            |       h8ffe710_0          69 KB  conda-forge
    libtiff-4.3.0              |       hc4061b1_3         1.1 MB  conda-forge
    markupsafe-2.1.1           |  py310he2412df_0          25 KB  conda-forge
    nbclient-0.5.13            |     pyhd8ed1ab_0          64 KB  conda-forge
    nbconvert-6.4.4            |  py310h5588dad_0         581 KB  conda-forge
    nbformat-5.2.0             |     pyhd8ed1ab_0         105 KB  conda-forge
    notebook-6.4.10            |     pyha770c72_0         6.3 MB  conda-forge
    numpy-1.22.3               |  py310hcae7c84_0         6.1 MB  conda-forge
    openssl-1.1.1n             |       h8ffe710_0         5.7 MB  conda-forge
    pandas-1.4.1               |  py310hf5e1058_0        11.0 MB  conda-forge
    pillow-9.0.1               |  py310h767b3fd_2        44.5 MB  conda-forge
    pip-22.0.4                 |     pyhd8ed1ab_0         1.5 MB  conda-forge
    prompt-toolkit-3.0.27      |     pyha770c72_0         252 KB  conda-forge
    prompt_toolkit-3.0.27      |       hd8ed1ab_0           5 KB  conda-forge
    python-3.10.2              |h9a09f29_4_cpython        15.7 MB  conda-forge
    pytz-2022.1                |     pyhd8ed1ab_0         242 KB  conda-forge
    pywinpty-2.0.5             |  py310h00ffb61_0         219 KB  conda-forge
    qt-5.12.9                  |       h556501e_6       106.1 MB  conda-forge
    qtpy-2.0.1                 |     pyhd8ed1ab_0          40 KB  conda-forge
    setuptools-60.10.0         |  py310h5588dad_0         1.2 MB  conda-forge
    soupsieve-2.3.1            |     pyhd8ed1ab_0          33 KB  conda-forge
    sqlite-3.37.1              |       h8ffe710_0         1.2 MB  conda-forge
    stack_data-0.2.0           |     pyhd8ed1ab_0          21 KB  conda-forge
    terminado-0.13.3           |  py310h5588dad_0          27 KB  conda-forge
    testpath-0.6.0             |     pyhd8ed1ab_0          85 KB  conda-forge
    tk-8.6.12                  |       h8ffe710_0         3.5 MB  conda-forge
    tzdata-2022a               |       h191b570_0         121 KB  conda-forge
    widgetsnbextension-3.6.0   |  py310h5588dad_0         1.2 MB  conda-forge
    zipp-3.7.0                 |     pyhd8ed1ab_1          12 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       252.5 MB

The following NEW packages will be INSTALLED:

  argon2-cffi        conda-forge/noarch::argon2-cffi-21.3.0-pyhd8ed1ab_0
  argon2-cffi-bindi~ conda-forge/win-64::argon2-cffi-bindings-21.2.0-py310he2412df_1
  asttokens          conda-forge/noarch::asttokens-2.0.5-pyhd8ed1ab_0
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  backcall           conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0
  backports          conda-forge/noarch::backports-1.0-py_2
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.4-pyhd8ed1ab_0
  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.10.0-pyha770c72_0
  bleach             conda-forge/noarch::bleach-4.1.0-pyhd8ed1ab_0
  brotli             conda-forge/win-64::brotli-1.0.9-h8ffe710_6
  brotli-bin         conda-forge/win-64::brotli-bin-1.0.9-h8ffe710_6
  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2021.10.8-h5b45459_0
  certifi            conda-forge/win-64::certifi-2021.10.8-py310h5588dad_1
  cffi               conda-forge/win-64::cffi-1.15.0-py310hcbf9ad4_0
  colorama           conda-forge/noarch::colorama-0.4.4-pyh9f0ad1d_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  cython             conda-forge/win-64::cython-0.29.28-py310h8a704f9_0
  debugpy            conda-forge/win-64::debugpy-1.5.1-py310h8a704f9_0
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
  defusedxml         conda-forge/noarch::defusedxml-0.7.1-pyhd8ed1ab_0
  entrypoints        conda-forge/noarch::entrypoints-0.4-pyhd8ed1ab_0
  executing          conda-forge/noarch::executing-0.8.3-pyhd8ed1ab_0
  flit-core          conda-forge/noarch::flit-core-3.7.1-pyhd8ed1ab_0
  fonttools          conda-forge/win-64::fonttools-4.31.2-py310he2412df_0
  freetype           conda-forge/win-64::freetype-2.10.4-h546665d_1
  icu                conda-forge/win-64::icu-69.1-h0e60522_0
  importlib-metadata conda-forge/win-64::importlib-metadata-4.11.3-py310h5588dad_0
  importlib_resourc~ conda-forge/noarch::importlib_resources-5.4.0-pyhd8ed1ab_0
  intel-openmp       conda-forge/win-64::intel-openmp-2022.0.0-h57928b3_3663
  ipykernel          conda-forge/win-64::ipykernel-6.9.2-py310hbbfc1a7_0
  ipython            conda-forge/win-64::ipython-8.1.1-py310h5588dad_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.7.0-pyhd8ed1ab_0 [...]

2022-03-24 11:18 UTC, LauWien commented
Just to be complete, the same with the newest conda version.
```

(message_env_2022) PS C:\Users\laura> conda update -n base -c defaults conda
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\laura\anaconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.12.0               |   py39haa95532_0        14.5 MB
    conda-package-handling-1.8.0|   py39hbd8134f_0         729 KB
    ------------------------------------------------------------
                                           Total:        15.2 MB

The following packages will be UPDATED:

  conda                               4.10.3-py39haa95532_0 --> 4.12.0-py39haa95532_0
  conda-package-han~                   1.7.3-py39h8cc25b3_1 --> 1.8.0-py39hbd8134f_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.12.0         | 14.5 MB   | ############################################################################ | 100%
conda-package-handli | 729 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(message_env_2022) PS C:\Users\laura> conda install message-ix
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\laura\anaconda3\envs\message_env_2022

  added / updated specs:
    - message-ix


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    beautifulsoup4-4.10.0      |     pyha770c72_0          77 KB  conda-forge
    cython-0.29.28             |  py310h8a704f9_0         1.9 MB  conda-forge
    entrypoints-0.4            |     pyhd8ed1ab_0           9 KB  conda-forge
    executing-0.8.3            |     pyhd8ed1ab_0          18 KB  conda-forge
    flit-core-3.7.1            |     pyhd8ed1ab_0          44 KB  conda-forge
    fonttools-4.31.2           |  py310he2412df_0         1.5 MB  conda-forge
    icu-69.1                   |       h0e60522_0        16.4 MB  conda-forge
    importlib-metadata-4.11.3  |  py310h5588dad_0          34 KB  conda-forge
    ipykernel-6.9.2            |  py310hbbfc1a7_0         186 KB  conda-forge
    ipython-8.1.1              |  py310h5588dad_0         1.1 MB  conda-forge
    ipywidgets-7.7.0           |     pyhd8ed1ab_0         103 KB  conda-forge
    jupyter_console-6.4.3      |     pyhd8ed1ab_0          23 KB  conda-forge
    jupyter_core-4.9.2         |  py310h5588dad_0         106 KB  conda-forge
    jupyterlab_widgets-1.1.0   |     pyhd8ed1ab_0         133 KB  conda-forge
    kiwisolver-1.4.0           |  py310h476a331_0          58 KB  conda-forge
    libclang-13.0.1            |default_h81446c8_0        23.7 MB  conda-forge
    libdeflate-1.10            |       h8ffe710_0          69 KB  conda-forge
    libtiff-4.3.0              |       hc4061b1_3         1.1 MB  conda-forge
    markupsafe-2.1.1           |  py310he2412df_0          25 KB  conda-forge
    nbclient-0.5.13            |     pyhd8ed1ab_0          64 KB  conda-forge
    nbconvert-6.4.4            |  py310h5588dad_0         581 KB  conda-forge
    nbformat-5.2.0             |     pyhd8ed1ab_0         105 KB  conda-forge
    notebook-6.4.10            |     pyha770c72_0         6.3 MB  conda-forge
    numpy-1.22.3               |  py310hcae7c84_0         6.1 MB  conda-forge
    openssl-1.1.1n             |       h8ffe710_0         5.7 MB  conda-forge
    pandas-1.4.1               |  py310hf5e1058_0        11.0 MB  conda-forge
    pillow-9.0.1               |  py310h767b3fd_2        44.5 MB  conda-forge
    pip-22.0.4                 |     pyhd8ed1ab_0         1.5 MB  conda-forge
    prompt-toolkit-3.0.27      |     pyha770c72_0         252 KB  conda-forge
    prompt_toolkit-3.0.27      |       hd8ed1ab_0           5 KB  conda-forge
    python-3.10.2              |h9a09f29_4_cpython        15.7 MB  conda-forge
    pytz-2022.1                |     pyhd8ed1ab_0         242 KB  conda-forge
    pywinpty-2.0.5             |  py310h00ffb61_0         219 KB  conda-forge
    qt-5.12.9                  |       h556501e_6       106.1 MB  conda-forge
    qtpy-2.0.1                 |     pyhd8ed1ab_0          40 KB  conda-forge
    setuptools-60.10.0         |  py310h5588dad_0         1.2 MB  conda-forge
    soupsieve-2.3.1            |     pyhd8ed1ab_0          33 KB  conda-forge
    sqlite-3.37.1              |       h8ffe710_0         1.2 MB  conda-forge
    stack_data-0.2.0           |     pyhd8ed1ab_0          21 KB  conda-forge
    terminado-0.13.3           |  py310h5588dad_0          27 KB  conda-forge
    testpath-0.6.0             |     pyhd8ed1ab_0          85 KB  conda-forge
    tk-8.6.12                  |       h8ffe710_0         3.5 MB  conda-forge
    tzdata-2022a               |       h191b570_0         121 KB  conda-forge
    widgetsnbextension-3.6.0   |  py310h5588dad_0         1.2 MB  conda-forge
    zipp-3.7.0                 |     pyhd8ed1ab_1          12 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       252.5 MB

The following NEW packages will be INSTALLED:

  argon2-cffi        conda-forge/noarch::argon2-cffi-21.3.0-pyhd8ed1ab_0
  argon2-cffi-bindi~ conda-forge/win-64::argon2-cffi-bindings-21.2.0-py310he2412df_1
  asttokens          conda-forge/noarch::asttokens-2.0.5-pyhd8ed1ab_0
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  backcall           conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0
  backports          conda-forge/noarch::backports-1.0-py_2
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.4-pyhd8ed1ab_0
  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.10.0-pyha770c72_0
  bleach             conda-forge/noarch::bleach-4.1.0-pyhd8ed1ab_0
  brotli             conda-forge/win-64::brotli-1.0.9-h8ffe710_6
  brotli-bin         conda-forge/win-64::brotli-bin-1.0.9-h8ffe710_6
  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2021.10.8-h5b45459_0
  certifi            conda-forge/win-64::certifi-2021.10.8-py310h5588dad_1
  cffi               conda-forge/win-64::cffi-1.15.0-py310hcbf9ad4_0
  colorama           conda-forge/noarch::colorama-0.4.4-pyh9f0ad1d_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  cython             conda-forge/win-64::cython-0.29.28-py310h8a704f9_0
  debugpy            conda-forge/win-64::debugpy-1.5.1-py310h8a704f9_0
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
  defusedxml         conda-forge/noarch::defusedxml-0.7.1-pyhd8ed1ab_0
  entrypoints        conda-forge/noarch::entrypoints-0.4-pyhd8ed1ab_0
  executing          conda-forge/noarch::executing-0.8.3-pyhd8ed1ab_0
  flit-core          conda-forge/noarch::flit-core-3.7.1-pyhd8ed1ab_0
  fonttools          conda-forge/win-64::fonttools-4.31.2-py310he2412df_0
  freetype           conda-forge/win-64::freetype-2.10.4-h546665d_1
  icu                conda-forge/win-64::icu-69.1-h0e60522_0
  importlib-metadata conda-forge/win-64::importlib-metadata-4.11.3-py310h5588dad_0
  importlib_resourc~ conda-forge/noarch::importlib_resources-5.4.0-pyhd8ed1ab_0
  intel-openmp       conda-forge/win-64::intel-openmp-2022.0.0-h57928b3_3663
  ipykernel          conda-forge/win-64::ipykernel-6.9.2-py310hbbfc1a7_0
  ipython            conda-forge/win-64::ipython-8.1.1-py310h5588dad_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.7.0-pyhd8ed1ab_0
  ixmp               conda-forge/win-64::ixmp-0.1.2-0
  jbig               conda-forge/win-64::jbig-2.1-h8d1472 [...]

2022-03-24 11:24 UTC, jakirkham commented
Looks like it is coming from your package cache. Would recommend running `conda clean -tipy` to clear out everything and try again.

2022-03-24 11:30 UTC, LauWien commented
> Looks like it is coming from your package cache. Would recommend running `conda clean -tipy` to clear out everything and try again.

Hm ;/
```

(message_env_2022) PS C:\Users\laura> conda clean -tipy
Cache location: C:\Users\laura\anaconda3\pkgs
Will remove the following tarballs:

C:\Users\laura\anaconda3\pkgs
-----------------------------
alabaster-0.7.12-pyhd3eb1b0_0.tar.bz2         16 KB
anaconda-2021.11-py39_0.tar.bz2               15 KB
anaconda-client-1.9.0-py39haa95532_0.conda     170 KB
anaconda-navigator-2.1.1-py39_0.tar.bz2      5.9 MB
anaconda-project-0.10.1-pyhd3eb1b0_0.conda     218 KB
anyio-2.2.0-py39haa95532_2.conda             125 KB
appdirs-1.4.4-pyhd3eb1b0_0.conda              12 KB
argh-0.26.2-py39haa95532_0.conda              36 KB
argon2-cffi-20.1.0-py39h2bbff1b_1.conda       49 KB
argon2-cffi-21.3.0-pyhd8ed1ab_0.tar.bz2       15 KB
argon2-cffi-bindings-21.2.0-py310he2412df_1.tar.bz2      34 KB
arrow-0.13.1-py39haa95532_0.conda             83 KB
asn1crypto-1.4.0-py_0.conda                   80 KB
astroid-2.6.6-py39haa95532_0.conda           313 KB
astropy-4.3.1-py39hc7d831d_0.conda           6.1 MB
asttokens-2.0.5-pyhd8ed1ab_0.tar.bz2          21 KB
async_generator-1.10-pyhd3eb1b0_0.tar.bz2      23 KB
atomicwrites-1.4.0-py_0.conda                 11 KB
attrs-21.2.0-pyhd3eb1b0_0.conda               46 KB
attrs-21.4.0-pyhd8ed1ab_0.tar.bz2             49 KB
autopep8-1.5.7-pyhd3eb1b0_0.conda             43 KB
babel-2.9.1-pyhd3eb1b0_0.conda               5.5 MB
backcall-0.2.0-pyh9f0ad1d_0.tar.bz2           13 KB
backcall-0.2.0-pyhd3eb1b0_0.tar.bz2           13 KB
backports-1.0-pyhd3eb1b0_2.conda             210 KB
backports-1.0-py_2.tar.bz2                     4 KB
backports.functools_lru_cache-1.6.4-pyhd3eb1b0_0.conda       9 KB
backports.functools_lru_cache-1.6.4-pyhd8ed1ab_0.tar.bz2       9 KB
backports.shutil_get_terminal_size-1.0.0-pyhd3eb1b0_3.conda      10 KB
backports.tempfile-1.0-pyhd3eb1b0_1.tar.bz2      11 KB
backports.weakref-1.0.post1-py_1.conda         8 KB
bcrypt-3.2.0-py39h196d8e1_0.conda            139 KB
beautifulsoup4-4.10.0-pyh06a4308_0.conda      85 KB
binaryornot-0.4.4-pyhd3eb1b0_1.conda         351 KB
bitarray-2.3.0-py39h2bbff1b_1.conda          142 KB
bkcharts-0.2-py39haa95532_0.conda            133 KB
black-19.10b0-py_0.conda                      86 KB
black-22.1.0-pyhd8ed1ab_0.tar.bz2            124 KB
blas-1.0-mkl.conda                             6 KB
bleach-4.0.0-pyhd3eb1b0_0.conda              113 KB
bleach-4.1.0-pyhd8ed1ab_0.tar.bz2            121 KB
blosc-1.21.0-h19a0ad4_0.conda                139 KB
bokeh-2.4.1-py39haa95532_0.conda             7.6 MB
bokeh-2.4.2-py310h5588dad_0.tar.bz2         13.7 MB
boto-2.49.0-py39haa95532_0.conda             1.5 MB
boto3-1.20.46-pyhd8ed1ab_0.tar.bz2            71 KB
botocore-1.23.46-pyhd8ed1ab_0.tar.bz2        5.2 MB
bottleneck-1.3.2-py39h7cc1a96_1.conda        107 KB
brotli-1.0.9-h8ffe710_6.tar.bz2               18 KB
brotli-1.0.9-ha925a31_2.conda                332 KB
brotli-bin-1.0.9-h8ffe710_6.tar.bz2           21 KB
brotlipy-0.7.0-py310he2412df_1003.tar.bz2     370 KB
brotlipy-0.7.0-py39h2bbff1b_1003.conda       411 KB
bzip2-1.0.8-h8ffe710_4.tar.bz2               149 KB
bzip2-1.0.8-he774522_0.conda                 113 KB
ca-certificates-2021.10.26-haa95532_2.conda     115 KB
ca-certificates-2021.10.8-h5b45459_0.tar.bz2     176 KB
cached-property-1.5.2-hd8ed1ab_1.tar.bz2       4 KB
cached-property-1.5.2-py_0.conda              11 KB
cached_property-1.5.2-pyha770c72_1.tar.bz2      11 KB
cairo-1.16.0-hb19e0ff_1008.tar.bz2           2.3 MB
cchardet-2.1.7-py310h8a704f9_2.tar.bz2       146 KB
certifi-2021.10.8-py310h5588dad_1.tar.bz2     145 KB
certifi-2021.10.8-py39haa95532_0.conda       152 KB
cffi-1.14.6-py39h2bbff1b_0.conda             224 KB
cffi-1.15.0-py310hcbf9ad4_0.tar.bz2          231 KB
cfitsio-3.470-he774522_6.conda               512 KB
chardet-4.0.0-py310h5588dad_2.tar.bz2        228 KB
chardet-4.0.0-py39haa95532_1003.conda        212 KB
charls-2.2.0-h6c2663c_0.conda                 82 KB
charset-normalizer-2.0.11-pyhd8ed1ab_0.tar.bz2      35 KB
charset-normalizer-2.0.4-pyhd3eb1b0_0.conda      35 KB
click-8.0.3-py310h5588dad_1.tar.bz2          150 KB
click-8.0.3-pyhd3eb1b0_0.conda                79 KB
cloudpickle-2.0.0-pyhd3eb1b0_0.conda          32 KB
cloudpickle-2.0.0-pyhd8ed1ab_0.tar.bz2        24 KB
clyent-1.2.2-py39haa95532_1.conda             21 KB
colorama-0.4.4-pyh9f0ad1d_0.tar.bz2           18 KB
colorama-0.4.4-pyhd3eb1b0_0.conda             21 KB
comtypes-1.1.10-py39haa95532_1002.conda      239 KB
conda-4.10.3-py39haa95532_0.tar.bz2          3.1 MB
conda-4.12.0-py39haa95532_0.conda           14.5 MB
conda-build-3.21.6-py39haa95532_0.conda      554 KB
conda-content-trust-0.1.1-pyhd3eb1b0_0.conda      56 KB
conda-env-2.6.0-1.conda                        3 KB
conda-pack-0.6.0-pyhd3eb1b0_0.conda           29 KB
conda-package-handling-1.7.3-py39h8cc25b3_1.conda     721 KB
conda-package-handling-1.8.0-py39hbd8134f_0.conda     729 KB
conda-repo-cli-1.0.4-pyhd3eb1b0_0.conda       47 KB
conda-token-0.3.0-pyhd3eb1b0_0.conda          10 KB
conda-verify-3.4.2-py_1.conda                 27 KB
console_shortcut-0.1.1-4.conda               277 KB
contextlib2-0.6.0.post1-pyhd3eb1b0_0.conda      13 KB
cookiecutter-1.7.2-pyhd3eb1b0_0.conda         86 KB
cryptography-3.4.8-py39h71e12ea_0.conda      638 KB
cryptography-36.0.1-py310ha857299_0.tar.bz2     1.2 MB
curl-7.78.0-h86230a5_0.conda                 132 KB
cycler-0.10.0-py39haa95532_0.conda            16 KB
cycler-0.11.0-pyhd8ed1ab_0.tar.bz2            10 KB
cython-0.29.24-py39h604cdb4_0.conda          1.8 MB
cython-0.29.27-py310h8a704f9_0.tar.bz2       1.9 MB
cytoolz-0.11.0-py39h2bbff1b_0.conda          294 KB
cytoolz-0.11.2-py310he2412df_1.tar.bz2       343 KB
daal4py-2021.3.0-py39h757b272_0.conda        7.6 MB
dal-2021.3.0-haa95532_564.conda             24.4 MB
dask-2021.10.0-pyhd3eb1b0_0.conda             19 KB
dask-2022.1.1-pyhd8ed1ab_0.tar.bz2             5 KB
dask-core-2021.10.0-pyhd3eb1b0_0.conda       718 KB
dask-core-2022.1.1-pyhd8ed1ab_0.tar.bz2      797 KB
dataclasses-0.8-pyh6d0b6a4_7.conda             8 KB
dataclasses-0.8-pyhc8e2a94_3.tar.bz2          10 KB
datapackage-1.15.2-pyh44b312d_0.tar.bz2       48 KB
debugpy-1.4.1-py39hd77b12b_0.conda           2.6 MB
debugpy-1.5.1-py310h8a704f9_0.tar.bz2        3.2 MB
decorator-5.1.0-pyhd3eb1b0_0.conda            14 KB
decorator-5.1.1-pyhd8ed1ab_0.tar.bz2          12 KB
defusedxml-0.7.1-pyhd3eb1b0_0.conda           23 KB
defusedxml-0.7.1-pyhd8ed1ab_0.tar.bz2         23 KB
descartes-1.1.0-py_4.tar.bz2                   7 KB
diff-match-patch-20200713-pyhd3eb1b0_0.conda      35 KB
distributed-2021.10.0-py39haa95532_0.conda    1013 KB
distributed-2022.1.1-py310h5588dad_0.tar.bz2     1.1 MB
docutils-0.17.1-py39haa95532_1.conda         693 KB
entrypoints-0.3-py39haa95532_0.conda          12 KB
entrypoints-0.3-pyhd8ed1ab_1003.tar.bz2        8 KB
et_xmlfile-1.0.1-py_1001.tar.bz2              11 KB
et_xmlfile-1.1.0-py39haa95532_0.conda         10 KB
executing-0.8.2-pyhd8ed1ab_0.tar.bz2          18 KB
expat-2.4.4-h39d44d4_0.tar.bz2               385 KB
fastcache-1.1.0-py39h196d8e1_0.conda          57 KB
filelock-3.3.1-pyhd3eb1b0_1.conda             12 KB
flake8-3.9.2-pyhd3eb1b0_0.conda              129 KB
flask-1.1.2-pyhd3eb1b0_0.tar.bz2              70 KB
flit-core-3.6.0-pyhd8ed1ab_0.tar.bz2          42 KB
font-ttf-dejavu-sans-mono-2.37-hab24e00_0.tar.bz2     388 KB
font-ttf-inconsolata-3.000-h77eed37_0.tar.bz2      94 KB
font-ttf-source-code-pro-2.038-h77eed37_0.tar.bz2     684 KB
font-ttf-ubuntu-0.83-hab24e00_0.tar.bz2      1.9 MB
fontconfig-2.13.94-h1989441_0.tar.bz2        2.0 MB
fonts-conda-ecosystem-1-0.tar.bz2              4 KB
fonts-conda-forge-1-0.tar.bz2                  4 KB
fonttools-4.25.0-pyhd3eb1b0_0.conda          632 KB
fonttools-4.29.0-py310he2412df_0.tar.bz2     1.5 MB
freetype-2.10.4-h546665d_1.tar.bz2           489 KB
freetype-2.10.4-hd3 [...]

2022-04-21 11:04 UTC, LauWien commented
Dear @isuruf, as the issue is unfortunately still not fixed, would you mind re-opening this PR or let me know where I should best file an issue where this will be dealt with? Many thanks in advance!

2022-04-21 20:59 UTC, isuruf commented
@LauWien,
```
conda create --quiet --name testenv --dry-run "message-ix" JPype1=1.2.1 pytest asyncssh sphinx -c conda-forge
```
works fine for me

2022-04-22 13:00 UTC, jaimergp commented
I ran this locally:
```
$ for platform in linux-64 osx-64 win-64; do
  echo $platform
  CONDA_SUBDIR=$platform conda create --quiet --name testenv --dry-run "message-ix" JPype1=1.2.1 pytest asyncssh sphinx -c conda-forge
done
```

It works ok on all platforms I think, can you double check the behaviour is the one you expect?


<details>

<summary>linux-64</summary>

```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/jrodriguez/.local/anaconda/envs/testenv

  added / updated specs:
    - asyncssh
    - jpype1=1.2.1
    - message-ix
    - pytest
    - sphinx

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  alabaster          conda-forge/noarch::alabaster-0.7.12-py_0
  alsa-lib           conda-forge/linux-64::alsa-lib-1.2.3-h516909a_0
  argon2-cffi        conda-forge/noarch::argon2-cffi-21.3.0-pyhd8ed1ab_0
  argon2-cffi-bindi~ conda-forge/linux-64::argon2-cffi-bindings-21.2.0-py39hb9d737c_2
  asttokens          conda-forge/noarch::asttokens-2.0.5-pyhd8ed1ab_0
  asyncssh           conda-forge/noarch::asyncssh-2.10.1-pyhd8ed1ab_0
  atk-1.0            conda-forge/linux-64::atk-1.0-2.36.0-h3371d22_4
  attrs              conda-forge/noarch::attrs-21.4.0-pyhd8ed1ab_0
  babel              conda-forge/noarch::babel-2.9.1-pyh44b312d_0
  backcall           conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0
  backports          conda-forge/noarch::backports-1.0-py_2
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.4-pyhd8ed1ab_0
  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.11.1-pyha770c72_0
  bleach             conda-forge/noarch::bleach-5.0.0-pyhd8ed1ab_0
  bokeh              conda-forge/linux-64::bokeh-2.4.2-py39hf3d152e_1
  boto3              conda-forge/noarch::boto3-1.21.44-pyhd8ed1ab_0
  botocore           conda-forge/noarch::botocore-1.24.45-pyhd8ed1ab_0
  brotli             conda-forge/linux-64::brotli-1.0.9-h166bdaf_7
  brotli-bin         conda-forge/linux-64::brotli-bin-1.0.9-h166bdaf_7
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py39hb9d737c_1004
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.10.8-ha878542_0
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
  cairo              conda-forge/linux-64::cairo-1.16.0-ha12eb4b_1010
  cchardet           conda-forge/linux-64::cchardet-2.1.7-py39he80948d_2
  certifi            conda-forge/linux-64::certifi-2021.10.8-py39hf3d152e_2
  cffi               conda-forge/linux-64::cffi-1.15.0-py39h4bc2ebd_0
  chardet            conda-forge/linux-64::chardet-4.0.0-py39hf3d152e_3
  charset-normalizer conda-forge/noarch::charset-normalizer-2.0.12-pyhd8ed1ab_0
  click              conda-forge/linux-64::click-8.1.2-py39hf3d152e_0
  cloudpickle        conda-forge/noarch::cloudpickle-2.0.0-pyhd8ed1ab_0
  colorama           conda-forge/noarch::colorama-0.4.4-pyh9f0ad1d_0
  cryptography       conda-forge/linux-64::cryptography-36.0.2-py39hd97740a_1
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  cytoolz            conda-forge/linux-64::cytoolz-0.11.2-py39hb9d737c_2
  dask               conda-forge/noarch::dask-2022.4.1-pyhd8ed1ab_0
  dask-core          conda-forge/noarch::dask-core-2022.4.1-pyhd8ed1ab_0
  datapackage        conda-forge/noarch::datapackage-1.15.2-pyh44b312d_0
  dbus               conda-forge/linux-64::dbus-1.13.6-h5008d03_3
  debugpy            conda-forge/linux-64::debugpy-1.6.0-py39h5a03fae_0
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
  defusedxml         conda-forge/noarch::defusedxml-0.7.1-pyhd8ed1ab_0
  descartes          conda-forge/noarch::descartes-1.1.0-py_4
  distributed        conda-forge/noarch::distributed-2022.4.1-pyhd8ed1ab_0
  docutils           conda-forge/linux-64::docutils-0.17.1-py39hf3d152e_1
  entrypoints        conda-forge/noarch::entrypoints-0.4-pyhd8ed1ab_0
  et_xmlfile         conda-forge/noarch::et_xmlfile-1.0.1-py_1001
  executing          conda-forge/noarch::executing-0.8.3-pyhd8ed1ab_0
  expat              conda-forge/linux-64::expat-2.4.8-h27087fc_0
  flit-core          conda-forge/noarch::flit-core-3.7.1-pyhd8ed1ab_0
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-hab24e00_0
  fontconfig         conda-forge/linux-64::fontconfig-2.14.0-h8e229c2_0
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0
  fonttools          conda-forge/linux-64::fonttools-4.33.0-py39hb9d737c_0
  freetype           conda-forge/linux-64::freetype-2.10.4-h0708190_1
  fribidi            conda-forge/linux-64::fribidi-1.0.10-h36c2ea0_0
  fsspec             conda-forge/noarch::fsspec-2022.3.0-pyhd8ed1ab_0
  gdk-pixbuf         conda-forge/linux-64::gdk-pixbuf-2.42.8-hff1cb4f_0
  genno              conda-forge/noarch::genno-1.11.0-pyhd8ed1ab_0
  gettext            conda-forge/linux-64::gettext-0.19.8.1-h73d1719_1008
  giflib             conda-forge/linux-64::giflib-5.2.1-h36c2ea0_2
  graphite2          conda-forge/linux-64::graphite2-1.3.13-h58526e2_1001
  graphviz           conda-forge/linux-64::graphviz-3.0.0-h5abf519_1
  greenlet           conda-forge/linux-64::greenlet-1.1.2-py39h5a03fae_2
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.20.1-hcf0ee16_1
  gstreamer          conda-forge/linux-64::gstreamer-1.20.1-hd4edc92_1
  gtk2               conda-forge/linux-64::gtk2-2.24.33-h90689f9_2
  gts                conda-forge/linux-64::gts-0.7.6-h64030ff_2
  harfbuzz           conda-forge/linux-64::harfbuzz-4.2.0-h40b6f09_0
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  iam-units          conda-forge/noarch::iam-units-2021.11.12-pyhd8ed1ab_0
  icu                conda-forge/linux-64::icu-69.1-h9c3ff4c_0
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  ijson              conda-forge/noarch::ijson-3.1.3-pyhd3deb0d_0
  imagesize          conda-forge/noarch::imagesize-1.3.0-pyhd8ed1ab_0
  importlib-metadata conda-forge/linux-64::importlib-metadata-4.11.3-py39hf3d152e_1
  importlib_metadata conda-forge/noarch::importlib_metadata-4.11.3-hd8ed1ab_1
  importlib_resourc~ conda-forge/noarch::importlib_resources-5.7.1-pyhd8ed1ab_0
  iniconfig          conda-forge/noarch::iniconfig-1.1.1-pyh9f0ad1d_0
  ipykernel          conda-forge/linux-64::ipykernel-6.13.0-py39hef51801_0
  ipython            conda-forge/linux-64::ipython-8.2.0-py39hf3d152e_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.7.0-pyhd8ed1ab_0
  isodate            conda-forge/noarch::isodate-0.6.1-pyhd8ed1ab_0
  ixmp               conda-forge/noarch::ixmp-3.4.0-pyhd8ed1ab_0
  jbig               conda-forge/linux-64::jbig-2.1-h7f98852_2003
  jedi               conda-forge/linux-64::jedi-0.18.1-py39hf3d152e_1
  jinja2             conda-forge/noarch::jinja2-3.1.1-pyhd8ed1ab_0
  jmespath           conda-forge/noarch::jmespath-1.0.0-pyhd8ed1ab_0
  jpeg               conda-forge/linux-64::jpeg-9e-h166bdaf_1
  jpype1             conda-forge/linux-64::jpype1-1.2.1-py39h1a9c180_0
  jsonlines          conda-forge/noarch::jsonlines-3.0.0-pyhd8ed1ab_0
  jsonpointer        conda-forge/noarch::jsonpointer-2.0-py_0 [...]

2022-04-22 13:19 UTC, LauWien commented
Dear both, thank you again for following up on this and re-opening!
> @LauWien,
> 
> ```
> conda create --quiet --name testenv --dry-run "message-ix" JPype1=1.2.1 pytest asyncssh sphinx -c conda-forge
> ```
> 
> works fine for me

As I said here https://github.com/conda-forge/admin-requests/pull/385#issuecomment-1027044838 this is also working for me. 
What is still not working is the simple `conda install message-ix`. Here conda chooses to install version 1.0.0. I thought with only this line the latest version should also get installed or am I mistaken?

2022-04-22 14:22 UTC, isuruf commented
Yes, I can reproduce with just `conda install message-ix`. I'm not sure what the exact problem is. Some issue with `current_repodata.json`. I'll merge if there's no objection from @jaimergp

2022-04-22 18:43 UTC, jaimergp commented
Oh I see; that's indeed weird. Let's merge and let's see if getting that out of the way helps! If the latest version does not get chosen that way... then something's definitely off.

2022-04-22 18:45 UTC, jaimergp commented
(There might be other ways of getting message-ix 1.0 deprioritized, maybe with some track_features, but I guess that's more trouble than it's worth at this point)

2022-04-22 18:50 UTC, merged

2022-04-25 07:35 UTC, khaeru commented
Echoing Laura, many thanks to all for the continued engagement and numerous other suggestions/pointers/explanations provided in order to exhaust other alternatives.